[book]
authors = ["Easy"]
language = "zh-cn"
multilingual = false
src = "src"
title = "一人企业方法论"

[output.html]
additional-css = ["theme/css/custom.css"]
git-repository-url = "https://github.com/KKKaniel/opc-methodology"
no-section-label = false
site-url = "/opc-methodology/"

[output.epub]
optional = true
cover-image = "src/images/opb-book-cover-2.1.jpg"
